import '../node_modules/slim-select/dist/slimselect.css';
import './js/header.js';
import './js/select.js';
import './js/loadProduct.js';
import './js/popularProducts.js';
import './js/discountProducts.js';
import './js/subscription.js';
import './js/pagination.js';
import './js/loadContent.js';
